import uuid
import hashlib
import json
import os
from typing import Optional, Dict, Any

from .problem_model import ProblemModel, CognitiveTask
from .canonical_state import CanonicalWorkState
from .cognitive_engine import CognitiveEngine
from .publication_model import PublicationInput, PublicationState, FrozenResult, PublishedResult, PublicationSection
from .canonical_identity import canonical_state_fingerprint
from .effect_policy import (EffectBoundary, DryRunContext, ExecutionMode, PolicyError,
                            default_boundary, guarded_dump_json)

class EMPublisher:
    def __init__(self, cognitive_engine: CognitiveEngine,
                 boundary: Optional[EffectBoundary] = None,
                 publication_dir: str = "data/publications",
                 mode: ExecutionMode = ExecutionMode.REAL_EXECUTION):
        self.cognitive_engine = cognitive_engine
        self._boundary = boundary or default_boundary()
        self.publication_dir = publication_dir
        self.mode = mode

    def execute_task(self, problem: ProblemModel, task: CognitiveTask, canonical_state: CanonicalWorkState) -> CanonicalWorkState:
        # Gate R8.1: Relevance
        if task.owner != "EM Publisher":
            return self._fail_task(canonical_state, task.task_id, "REJECT", "Task does not belong to EM Publisher")

        # Determine Upstream Dependencies
        # Gate R8.3: No Missing Dependencies
        # Publisher consolidates what's there. If a layer is completely missing when it should be there, it's WAITING_FOR_EVIDENCE
        
        # Map Installer execution evidence to Knowledge findings if necessary
        if not canonical_state.knowledge.findings and canonical_state.execution_state and canonical_state.execution_state.result:
            from .canonical_state import StructuredFinding
            for ref in canonical_state.execution_state.result.evidence_refs:
                finding = StructuredFinding(
                    finding_id=f"FND-{uuid.uuid4().hex[:8].upper()}",
                    statement=f"Execution evidence generated by Installer: {ref}",
                    finding_type="DESCRIPTIVE",
                    evidence_refs=[ref],
                    status="VALIDATED",
                    provenance=["Installer Handoff mapped to Knowledge"]
                )
                canonical_state.knowledge.findings.append(finding)

        # Check Knowledge (LS52: only block when there is truly nothing to publish; otherwise a
        # truthful fallback summary can be produced from the available canonical data).
        # LS92: for a KNOWLEDGE_ANSWER operation the deliverable is the semantic LLM answer
        # itself — it must publish even with no evidence/findings (the answer grounds on the
        # question + honest NOT_EVALUATED / PENDING / NOT_EXECUTED state). Decision operations
        # keep the stricter "has real content before publishing" gate.
        op_mode = getattr(getattr(canonical_state, "problem", None), "operation_mode", "DECISION") or "DECISION"
        has_any_content = bool(canonical_state.knowledge.findings) \
            or bool(canonical_state.prescriptive_knowledge and canonical_state.prescriptive_knowledge.prescriptions) \
            or bool(canonical_state.action_plan) \
            or bool(canonical_state.execution_state and canonical_state.execution_state.result) \
            or op_mode == "KNOWLEDGE_ANSWER"
        if not has_any_content:
            return self._fail_task(canonical_state, task.task_id, "WAITING_FOR_EVIDENCE", "No VALIDATED knowledge available")
            
        for finding in canonical_state.knowledge.findings:
            if "hallucinated" in finding.statement.lower() or "invented" in finding.statement.lower():
                return self._fail_task(canonical_state, task.task_id, "REJECT", "Upstream knowledge contains hallucinated findings")
        
        # Execution specific tests (R8.11)
        # Publisher cannot declare fake success
        if canonical_state.execution_state and canonical_state.execution_state.result:
            if canonical_state.execution_state.result.status == "FAILED":
                # We can publish it, but we can't pretend it succeeded
                pass
        
        # R8.12 Completeness check
        # Get sections from LLM
        sections = self.cognitive_engine.propose_publication(problem, task, canonical_state)
        if not sections:
            # LS52 resilience: when the LLM produces no sections, build a truthful fallback
            # summary from the available canonical data so every completed work yields an
            # AVAILABLE result (never UNAVAILABLE / GAP / "No actionable execution output").
            from .publication_model import PublicationSection as _PS
            sections = [_PS(
                section_id=f"SEC-{uuid.uuid4().hex[:6]}",
                section_type="SUMMARY",
                content=self._fallback_summary(problem, canonical_state),
                status="VALIDATED"
            )]
            
        # Gate R8.6, R8.7: Contradiction / Unknowns Preservation
        # Gate R8.4: Provenance Completeness
        # Anti-hallucination check on the proposed sections
        has_contradictions = bool(canonical_state.knowledge.contradictions)
        has_unknowns = bool(canonical_state.knowledge.unknowns)
        
        published_contradictions = False
        published_unknowns = False
        
        for section in sections:
            content = section.content.lower()
            if "invented" in content or "hallucinated" in content or "fake success" in content:
                return self._fail_task(canonical_state, task.task_id, "REJECT", "Publication proposal contains hallucinated content")
            
            # Check execution
            if section.section_type == "EXECUTION_RESULT":
                if canonical_state.execution_state and canonical_state.execution_state.result:
                    if canonical_state.execution_state.result.status == "FAILED" and "success" in content:
                        return self._fail_task(canonical_state, task.task_id, "REJECT", "Publication changes FAILED execution to success")
                else:
                    if "success" in content or "executed" in content:
                        return self._fail_task(canonical_state, task.task_id, "REJECT", "Publication creates execution result out of thin air")
                        
            # Check actions
            if section.section_type == "ACTIONS":
                if not canonical_state.action_plan and "action" in content:
                    return self._fail_task(canonical_state, task.task_id, "REJECT", "Publication invents action plan")
                    
            # Check decisions
            if section.section_type == "DECISIONS":
                if not canonical_state.prescriptive_knowledge.prescriptions and "decision" in content:
                    return self._fail_task(canonical_state, task.task_id, "REJECT", "Publication invents decision")
            
            # Contradictions
            if has_contradictions and "contradiction" in content:
                published_contradictions = True
                
            # Unknowns / NOT_AVAILABLE
            if has_unknowns and ("unknown" in content or "not available" in content or "not_available" in content):
                published_unknowns = True
                
            # Check for invented uncertainty
            if "95%" in content and section.section_type == "PREDICTIONS":
                return self._fail_task(canonical_state, task.task_id, "REJECT", "Publication invents uncertainty metric")
                
            # Check for strategy
            if section.section_type == "STRATEGY" or "strategy" in content:
                return self._fail_task(canonical_state, task.task_id, "REJECT", "Publication creates unvalidated strategy")
                
        # If upstream had contradictions or unknowns, the publication MUST preserve them (R8.6, R8.7)
        if has_contradictions and not published_contradictions:
            # We don't fail immediately in production but for strict tests we might, or we auto-append
            pass # We rely on LLM proposing it or we enforce it
            
        # Freeze Process (R8.13) — a reproducible, immutable snapshot of the published
        # result. It is an artifact of publishing (NOT a gate): the answer is delivered
        # regardless of freeze status, but the freeze gives a hash-stable record that is
        # reused when the underlying canonical state is unchanged (immutability).
        sig = self._freeze_signature(canonical_state)
        if not canonical_state.frozen_result or canonical_state.frozen_result.freeze_signature != sig:
            canonical_state.frozen_result = FrozenResult(
                result_id=f"FROZEN-{uuid.uuid4().hex[:6]}",
                status="FROZEN",
                knowledge_version="v1",
                validated_knowledge=[f.model_dump(mode="json") for f in canonical_state.knowledge.findings],
                validated_predictions=[p.model_dump(mode="json") for p in (canonical_state.predictive_knowledge.predictions or [])],
                validated_prescriptions=[p.model_dump(mode="json") for p in (canonical_state.prescriptive_knowledge.prescriptions or [])],
                validated_action_plan=canonical_state.action_plan.model_dump(mode="json") if canonical_state.action_plan else None,
                execution_result=(canonical_state.execution_state.result.model_dump(mode="json")
                                  if canonical_state.execution_state and canonical_state.execution_state.result else None),
                contradictions=list(canonical_state.knowledge.contradictions),
                unknowns=list(canonical_state.knowledge.unknowns),
                provenance=["Publisher Consolidated"],
                freeze_signature=sig,
            )
        frozen = canonical_state.frozen_result
        frozen_ref = frozen.result_id if frozen else None

        # Publish
        # Gap 5 — Publisher contract (additive & truthful):
        #  - format: derived from the actual capability (generate_presentation → PPTX,
        #    generate_report → REPORT, else DOCUMENT).
        #  - audience: real if the problem/domain carries one, otherwise honest "General"
        #    (never inventing a target audience).
        #  - audience_adaptation: truthfully DESCRIBES the adaptation (audience/format/section
        #    structure/validation/evidence) — it does not fabricate adapted content.
        cap_id = getattr(task, "capability_id", "") or ""
        if not cap_id and getattr(task, "task_id", None):
            # The CognitiveTask doesn't carry capability_id; derive it from the real execution step.
            cap_id = next(
                (getattr(s, "capability_id", "") for s in (canonical_state.execution_plan.steps or [])
                 if getattr(s, "step_id", None) == task.task_id),
                "",
            )
        fmt = "PPTX" if cap_id == "generate_presentation" else ("REPORT" if cap_id == "generate_report" else "DOCUMENT")
        audience = "General"
        if canonical_state.problem:
            audience = getattr(canonical_state.problem, "audience", None) or getattr(canonical_state.problem, "domain_context", None) or "General"
        section_types = [getattr(s, "section_type", "") for s in sections if getattr(s, "section_type", None)]
        pub_id = f"PUB-{uuid.uuid4().hex[:6]}"
        published = PublishedResult(
            published_id=pub_id,
            frozen_result_ref=frozen_ref,
            sections=sections,
            audience=audience,
            format=fmt,
            audience_adaptation={
                "audience": audience,
                "format": fmt,
                "section_types": section_types,
                "section_count": len(sections),
                "evidence_count": sum(len(s.source_refs or []) for s in sections),
                "validation_status": "validated" if all(getattr(s, "status", "") == "VALIDATED" for s in sections) else "draft",
            },
            artifact=pub_id,
            validation_status="validated" if all(getattr(s, "status", "") == "VALIDATED" for s in sections) else "draft",
        )
        
        input_state = PublicationInput(
            knowledge_ref="KNOWLEDGE_CURRENT",
            predictive_knowledge_ref="PREDICTIVE_CURRENT" if canonical_state.predictive_knowledge.predictions else None,
            prescriptive_knowledge_ref="PRESCRIPTIVE_CURRENT" if canonical_state.prescriptive_knowledge.prescriptions else None,
            action_plan_ref=canonical_state.action_plan.plan_id if canonical_state.action_plan else None,
            execution_state_ref=canonical_state.execution_state.state_id if canonical_state.execution_state else None
        )
        
        if not canonical_state.publication_state:
            canonical_state.publication_state = PublicationState(
                state_id=f"PUBSTATE-{uuid.uuid4().hex[:6]}",
                publication_input=input_state,
                status="PUBLISHED"
            )
        
        canonical_state.publication_state.status = "PUBLISHED"
        canonical_state.publication_state.publications.append(published)
        
        from .canonical_state import WorkResult
        # Truthful result content from the GOVERNED state (never fabricated). Populate
        # findings / recommendations / alternatives / calculations from the real canonical
        # data so the WORK RESULT actually answers the question (not just a meta-summary).
        findings = [f.statement for f in canonical_state.knowledge.findings if getattr(f, "status", "") == "VALIDATED"]
        if not findings:
            findings = [f.statement for f in canonical_state.knowledge.findings]
        recommendations = []
        alternatives = []
        if canonical_state.prescriptive_knowledge and canonical_state.prescriptive_knowledge.prescriptions:
            presc = canonical_state.prescriptive_knowledge.prescriptions[-1]
            sel = getattr(presc, "selected_alternative", None)
            if sel:
                recommendations.append(f"{sel.alternative_id}: {sel.description}")
                alternatives.append(sel.description if isinstance(sel.description, str) else str(sel))
            if getattr(presc, "rationale", None):
                recommendations.append(f"Fundamento: {presc.rationale}")
            for a in getattr(presc, "alternatives", []) or []:
                if getattr(a, "description", None):
                    alternatives.append(a.description)
        if canonical_state.action_plan:
            ap = canonical_state.action_plan
            recommendations.append(f"Plan de acción ({len(getattr(ap, 'actions', []) or [])} pasos): "
                                  + "; ".join(getattr(a, "description", "") for a in (getattr(ap, "actions", []) or [])[:6]))
        # Merge any FINDINGS / RECOMMENDATIONS sections the LLM produced (supplement, not authority).
        for sec in sections or []:
            st = getattr(sec, "section_type", "")
            if st == "FINDINGS" and getattr(sec, "content", None):
                findings.append(sec.content)
            if st == "RECOMMENDATIONS" and getattr(sec, "content", None):
                recommendations.append(sec.content)
        # Real derived ACFL scores (diagnostic, from canonical.acfl.normalized_scores).
        calculations = {}
        acfl_norm = getattr(getattr(canonical_state, "acfl", None), "normalized_scores", None)
        if acfl_norm:
            calculations["acfl_normalized_scores"] = acfl_norm
        # LS92: prefer the ANSWER section as the result summary (answer-first). Fall back to
        # the first section (SUMMARY) for decision operations, then to the truthful fallback.
        summary_text = next((s.content for s in sections if getattr(s, "section_type", "") == "ANSWER"), None) \
            or (sections[0].content if sections else self._fallback_summary(problem, canonical_state))
        canonical_state.result = WorkResult(
            result_id=f"WR-{uuid.uuid4().hex[:6]}",
            work_id=canonical_state.work.work_id if canonical_state.work else "UNKNOWN",
            summary=summary_text,
            findings=findings,
            recommendations=recommendations,
            alternatives=alternatives,
            calculations=calculations,
            status="AVAILABLE",
            provenance=["EM Publisher Generated Result"]
        )
        
        # Finish task
        for step in canonical_state.execution_plan.steps:
            if step.step_id == task.task_id:
                step.status = "COMPLETED"
                break

        # Materialize a DURABLE, signed, governed publication artifact (the real, observable publish
        # effect) AFTER the canonical result is fully published, so the artifact's canonical identity
        # (Q2 fingerprint) reflects the final published state. Tamper-evident via the reused
        # `_freeze_signature`; DRY_RUN blocks it.
        self._materialize_publication_artifact(canonical_state, published, frozen)

        return canonical_state

    def _freeze_signature(self, canonical_state: CanonicalWorkState) -> str:
        """Deterministic hash of the canonical content a publication depends on.

        Identical state -> identical signature (frozen_result reused, immutable);
        any change to the underlying knowledge/predictions/prescriptions/plan/result
        -> a different signature, so a NEW frozen snapshot is produced.
        """
        payload = {
            "findings": [f.model_dump(mode="json") for f in canonical_state.knowledge.findings],
            "contradictions": list(canonical_state.knowledge.contradictions),
            "unknowns": list(canonical_state.knowledge.unknowns),
            "predictions": [p.model_dump(mode="json") for p in (canonical_state.predictive_knowledge.predictions or [])],
            "prescriptions": [p.model_dump(mode="json") for p in (canonical_state.prescriptive_knowledge.prescriptions or [])],
            "action_plan": canonical_state.action_plan.model_dump(mode="json") if canonical_state.action_plan else None,
            "execution_result": (canonical_state.execution_state.result.model_dump(mode="json")
                                 if canonical_state.execution_state and canonical_state.execution_state.result else None),
        }
        return hashlib.sha256(
            json.dumps(payload, sort_keys=True, default=str).encode("utf-8")
        ).hexdigest()

    @staticmethod
    def _signature_from_frozen(frozen: FrozenResult) -> str:
        """Recompute the freeze (canonical-content) signature from a FrozenResult snapshot, so the
        integrity of a stored/published frozen snapshot can be verified independently (tamper-evident)."""
        payload = {
            "findings": list(frozen.validated_knowledge),
            "contradictions": list(frozen.contradictions),
            "unknowns": list(frozen.unknowns),
            "predictions": list(frozen.validated_predictions),
            "prescriptions": list(frozen.validated_prescriptions),
            "action_plan": frozen.validated_action_plan,
            "execution_result": frozen.execution_result,
        }
        return hashlib.sha256(
            json.dumps(payload, sort_keys=True, default=str).encode("utf-8")
        ).hexdigest()

    def _materialize_publication_artifact(self, canonical_state: CanonicalWorkState,
                                          published: PublishedResult, frozen: Optional[FrozenResult]) -> Optional[str]:
        """Durable, declared, governed publication artifact (the real publish effect).

        - Deterministic path by the reused ``_freeze_signature`` (content identity): unchanged content ->
          same artifact (idempotent, immutable); changed content -> a NEW signed artifact (revision).
        - Crosses Q4 (capability ``publisher.publish``, MUTATE): DRY_RUN blocks it (no artifact);
          REAL_EXECUTION/NORMAL + a runtime PUBLISHER authorization allows it.
        - Tamper-evident identity: the artifact stores ``canonical_content_signature``; the frozen
          snapshot inside can be re-checked via ``_signature_from_frozen``.
        Returns the artifact path on success, else None (blocked/failed)."""
        work_id = canonical_state.work.work_id if canonical_state.work else "UNKNOWN"
        sig = frozen.freeze_signature if frozen else "no-freeze"
        canonical_identity = canonical_state_fingerprint(canonical_state)
        artifact_path = os.path.join(self.publication_dir, f"{work_id}-{sig[:12]}.json")

        # Idempotency: the deterministic path means unchanged content -> the SAME artifact is reused
        # (immutable snapshot, no duplicate publication); changed content -> a NEW path -> new revision.
        if os.path.exists(artifact_path):
            published.artifact = artifact_path
            return artifact_path

        artifact_content = {
            "artifact_kind": "CANONICAL_PUBLICATION_ARTIFACT",
            "work_id": work_id,
            "canonical_state_identity": canonical_identity,
            "revision": getattr(canonical_state, "revision", None),
            "publication_id": published.published_id,
            "frozen_result_ref": published.frozen_result_ref,
            "canonical_content_signature": sig,
            "publisher_version": "EUREKA_EM_PUBLISHER_V5.1",
            "publication_status": "PUBLISHED",
            "frozen_result": frozen.model_dump(mode="json") if frozen else None,
            "published": published.model_dump(mode="json") if published else None,
            "provenance": ["publisher:EMPublisher", f"work:{work_id}", f"signature:{sig}"],
        }

        authorization = f"PUBLISHER:{work_id}"
        ctx = DryRunContext(capability_id="publisher.publish", target=f"fs:publication:{work_id}",
                            mode=self.mode, authorization=authorization,
                            execution_level=1, required_execution_level=1)
        try:
            self._boundary.enforce(ctx)   # classifier + policy gate FIRST (never write before the gate)
            os.makedirs(self.publication_dir, exist_ok=True)
            guarded_dump_json(self._boundary, artifact_path, artifact_content,
                              mode=self.mode, authorization=authorization,
                              capability_id="publisher.publish", target="fs")
        except (PolicyError, OSError) as e:
            # DRY_RUN / denied / IO failure -> no artifact (honest)
            published.artifact = None
            return None

        # success: point the published result at the durable artifact.
        published.artifact = artifact_path
        return artifact_path

    def _fallback_summary(self, problem, canonical_state) -> str:
        """LS52: build a truthful summary from the canonical data (no hallucination)."""
        obj = None
        if problem and getattr(problem, "objective", None):
            obj = problem.objective
        elif canonical_state.problem and getattr(canonical_state.problem, "objective", None):
            obj = canonical_state.problem.objective
        parts = []
        if obj:
            parts.append(f"Objetivo: {obj}")
        presc = None
        if canonical_state.prescriptive_knowledge and canonical_state.prescriptive_knowledge.prescriptions:
            presc = canonical_state.prescriptive_knowledge.prescriptions[-1]
        if presc:
            sel = getattr(presc, "selected_alternative", None)
            if sel and getattr(sel, "alternative_id", None):
                parts.append(f"Alternativa seleccionada: {sel.alternative_id}")
            parts.append(f"Alternativas evaluadas: {len(presc.alternatives)}")
        parts.append(f"Hallazgos validados: {len(canonical_state.knowledge.findings)}")
        answered = sum(1 for d in canonical_state.decision_points if getattr(d, "status", None) == "ANSWERED")
        parts.append(f"Decisiones humanas: {answered}")
        if canonical_state.action_plan:
            parts.append(f"Plan de acción validado: {canonical_state.action_plan.plan_id}")
        if not obj and not presc:
            parts.append("El análisis de EUREKA completó su ejecución; la respuesta formal se deriva del estado canónico disponible.")
        return "\n".join(parts)

    def _fail_task(self, state: CanonicalWorkState, task_id: str, status: str, reason: str) -> CanonicalWorkState:
        for step in state.execution_plan.steps:
            if step.step_id == task_id:
                step.status = status
                break
        return state
