import React, { useState, useEffect } from 'react';
import { useWorkStore } from '../../store/workStore';

export default function StoryEngineCanvas() {
  const activeWork = useWorkStore((state) => state.activeWork);
  const [activeAct, setActiveAct] = useState<string>('');
  const [acts, setActs] = useState<any[]>([]);

  useEffect(() => {
    const s = activeWork?.state as any;
    if (s?.story?.arc) {
      const backendActs = s.story.arc.map((a: any, idx: number) => ({
        id: `ACT_0${idx + 1}`,
        title: a.phase,
        summary: a.content || 'Content generated by StoryEngine based on the Work State.',
        source: a.source || 'NOT_AVAILABLE',
        authority: a.authority || 'GAP',
      }));
      setActs(backendActs);
      if (backendActs.length > 0) setActiveAct(backendActs[0].id);
    }
  }, [activeWork]);

  if (!acts.length) return null;

  return (
    <div className="fabric-panel p-6 bg-[var(--eureka-surface)] border border-[var(--eureka-spatial-hairline)] h-full flex flex-col">
      <h3 className="text-xs font-bold text-[var(--eureka-text-display)] mb-4 tracking-widest flex items-center gap-2">
        <span className="w-2 h-2 rounded-full bg-purple-500"></span>
        EUREKA STORY
      </h3>

      <div className="flex-1 flex overflow-hidden">
        {/* Story Navigator */}
        <div className="w-48 border-r border-[var(--eureka-spatial-hairline)] pr-4 overflow-y-auto space-y-4">
          {acts.map((act) => (
            <div 
              key={act.id}
              onClick={() => setActiveAct(act.id)}
              className={`cursor-pointer border-l-2 pl-3 py-1 transition-colors ${
                activeAct === act.id 
                  ? 'border-purple-500 text-white' 
                  : 'border-[var(--eureka-spatial-hairline)] text-[var(--eureka-text-label)] hover:text-[var(--eureka-text-section)]'
              }`}
            >
              <div className="text-[10px] font-bold">{act.id.replace('_', ' ')}</div>
              <div className="text-xs">{act.title}</div>
            </div>
          ))}
        </div>

        {/* Story Content Area */}
        <div className="flex-1 pl-6 flex flex-col justify-center space-y-4">
          <div className="text-sm text-purple-400 font-bold">{activeAct.replace('_', ' ')}</div>
          <h4 className="text-2xl text-[var(--eureka-text-display)] font-light">
            {acts.find(a => a.id === activeAct)?.title}
          </h4>
          <p className="text-[var(--eureka-text-section)]">
            {acts.find(a => a.id === activeAct)?.summary}
          </p>
          
          <div className="mt-8 p-4 bg-[#111116] border border-[var(--eureka-spatial-hairline)] rounded text-xs text-[var(--eureka-text-label)] space-y-1">
            <div className="flex items-center gap-2">
              <span className="text-purple-400">Artefacto fuente:</span>
              <span className="text-[var(--eureka-text-section)]">{acts.find(a => a.id === activeAct)?.source}</span>
            </div>
            <div className="flex items-center gap-2">
              <span className="text-purple-400">Autoridad:</span>
              <span className="text-[var(--eureka-text-section)]">{acts.find(a => a.id === activeAct)?.authority}</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
