from pydantic import BaseModel, Field, ConfigDict
from typing import List, Dict, Any, Optional

class AgentToolCall(BaseModel):
    """
    Represents a tool call generated by the LLM.
    IMPORTANT: This is UNTRUSTED COGNITIVE OUTPUT. It does not confer execution authority.
    """
    id: str
    name: str
    arguments: str

class AgentRequest(BaseModel):
    """
    Represents an agnostic request to an Agent Provider.
    """
    request_id: str = Field(description="Unique identifier for the request, used for traceability")
    messages: List[Dict[str, str]] = Field(description="List of messages in standard role/content format")
    system_context: str = Field(default="", description="System prompt or initial context")
    tools: Optional[List[Dict[str, Any]]] = Field(default=None, description="Definitions of available tools")
    response_format: Optional[Dict[str, str]] = Field(default=None, description="Optional response format constraint, e.g., {'type': 'json_object'}")
    model: str = Field(default="mock-model", description="The requested model name")
    metadata: Dict[str, Any] = Field(default_factory=dict)

class AgentResponse(BaseModel):
    """
    Represents the agnostic response from an Agent Provider.
    IMPORTANT: Content and tool_calls within this response are strictly UNTRUSTED COGNITIVE OUTPUT.
    They carry ZERO authority for selection, prescription, or execution.
    """
    model_config = ConfigDict(frozen=True)

    content: Optional[str] = Field(description="The main text response from the model")
    tool_calls: Optional[List[AgentToolCall]] = Field(default=None, description="Tool calls proposed by the model")
    finish_reason: str = Field(description="Reason why the model stopped generating")
    provider: str = Field(description="The provider that fulfilled this response (e.g., 'DEEPSEEK', 'MOCK')")
    model: str = Field(description="The actual model used")
    usage: Dict[str, int] = Field(default_factory=dict, description="Token usage statistics")
    traceability_id: str = Field(description="Links back to the original AgentRequest request_id")
    provenance: Dict[str, Any] = Field(description="Information about how/when this was generated")
